version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biro-umum-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - biro-network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: biro-umum-nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - biro-network
    depends_on:
      - app

  db:
    image: postgres:14
    container_name: biro-umum-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: biro_umum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - biro-network

volumes:
  dbdata:

networks:
  biro-network:
